export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_STAFF_LIST_SALARY = 'GET_STAFF_LIST_SALARY';
export const GET_STAFF_INFORMATIONS = 'GET_STAFF_INFORMATIONS';
export const GET_STAFF_TIMESHEET = 'GET_STAFF_TIMESHEET';

